### ISSUE TITLE
dependencies are wrong

### ISSUE THREAD

**Issue by macrozone** [Scrivito/scroll-to-fragment#12]
hi, there is a misstake in the package.json

- history should be in `dependencies`
- @types/history should be in  `devDependencies`

**Comment by dcsaszar** [comment]
Hey @macrozone, 

let me explain the idea:

* `history` should not be a dependency, because you can use `scroll-to-fragment` without the `history` option. If your app wants to use this option, it becomes a dependency of the app.
* `@types/history` is a dependency, because the generated types _do_ refer to the `History` type. (`import * as History from "history"`)

So far, this does the job.
I'm open for suggestions though.

**Comment by dcsaszar** [comment]
Closing for now. This might be a valid issue but I think it's good enough at the moment.

**Comment by dcsaszar** [comment]
Reopening. I realised that `scroll-to-fragment` is not compatible with `history` version 5.

Having some form of compatibility indicator in the dependencies makes sense. We'll see what we can do here.
